// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactWithASP.Data;

#nullable disable

namespace ReactWithASP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250218093705_FixReasonDetailModel")]
    partial class FixReasonDetailModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("ReactWithASP.Models.Case", b =>
                {
                    b.Property<int>("caseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("agentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("caseComments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("caseDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("caseNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("caseStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("categoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("clientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("detailId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("reasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("caseId");

                    b.HasIndex("categoryId");

                    b.HasIndex("clientId");

                    b.HasIndex("detailId");

                    b.HasIndex("reasonId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("ReactWithASP.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ReactWithASP.Models.Client", b =>
                {
                    b.Property<int>("clientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("clientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("clientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ReactWithASP.Models.Detail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetailId");

                    b.HasIndex("ReasonId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("ReactWithASP.Models.Reason", b =>
                {
                    b.Property<int>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReasonId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("ReactWithASP.Models.Case", b =>
                {
                    b.HasOne("ReactWithASP.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactWithASP.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactWithASP.Models.Detail", "Detail")
                        .WithMany()
                        .HasForeignKey("detailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactWithASP.Models.Reason", "Reason")
                        .WithMany()
                        .HasForeignKey("reasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Client");

                    b.Navigation("Detail");

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("ReactWithASP.Models.Detail", b =>
                {
                    b.HasOne("ReactWithASP.Models.Reason", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("ReactWithASP.Models.Reason", b =>
                {
                    b.HasOne("ReactWithASP.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
